---
title: "Final Project"
output: html_notebook
authors: Joshua Allessio, Kashyap Vallur and Marco Camalich
---
 
```{r}
required_packages <- c("tidyverse", "janitor", "here", "openmeteo", "lubridate", "forcats")

for (packages in required_packages) {
  if (!require(packages, character.only = TRUE)) {
    install.packages(packages, dependencies = TRUE)
    library(packages, character.only = TRUE)
  }
}

if (all(sapply(required_packages, requireNamespace, quietly = TRUE))) {
  cat("All required packages are loaded.\n")
} else {
  warning("Some packages failed to load.")
}

```

```{r}
df_01=read_csv(here("data_raw", "202301-capitalbikeshare-tripdata.csv"))%>%
 filter(
    !is.na(start_station_name) & !is.na(start_station_id) & start_station_name != "" & start_station_id != "" &
    !is.na(end_station_name) & !is.na(end_station_id) & end_station_name != "" & end_station_id != "" &
    !is.na(start_lat) & !is.na(start_lng) & !is.na(end_lng)
  )
df_02=read_csv(here("data_raw", "202302-capitalbikeshare-tripdata.csv"))%>%
  filter(
    !is.na(start_station_name) & !is.na(start_station_id) & start_station_name != "" & start_station_id != "" &
    !is.na(end_station_name) & !is.na(end_station_id) & end_station_name != "" & end_station_id != "" &
    !is.na(start_lat) & !is.na(start_lng) & !is.na(end_lng)
  )
df_03=read_csv(here("data_raw", "202303-capitalbikeshare-tripdata.csv"))%>%
  filter(
    !is.na(start_station_name) & !is.na(start_station_id) & start_station_name != "" & start_station_id != "" &
    !is.na(end_station_name) & !is.na(end_station_id) & end_station_name != "" & end_station_id != "" &
    !is.na(start_lat) & !is.na(start_lng) & !is.na(end_lng)
  )
df_04=read_csv(here("data_raw", "202304-capitalbikeshare-tripdata.csv"))%>%
  filter(
    !is.na(start_station_name) & !is.na(start_station_id) & start_station_name != "" & start_station_id != "" &
    !is.na(end_station_name) & !is.na(end_station_id) & end_station_name != "" & end_station_id != "" &
    !is.na(start_lat) & !is.na(start_lng) & !is.na(end_lng)
  )
df_05=read_csv(here("data_raw", "202305-capitalbikeshare-tripdata.csv"))%>%
  filter(
    !is.na(start_station_name) & !is.na(start_station_id) & start_station_name != "" & start_station_id != "" &
    !is.na(end_station_name) & !is.na(end_station_id) & end_station_name != "" & end_station_id != "" &
    !is.na(start_lat) & !is.na(start_lng) & !is.na(end_lng)
  )
df_06=read_csv(here("data_raw", "202306-capitalbikeshare-tripdata.csv"))%>%
  filter(
    !is.na(start_station_name) & !is.na(start_station_id) & start_station_name != "" & start_station_id != "" &
    !is.na(end_station_name) & !is.na(end_station_id) & end_station_name != "" & end_station_id != "" &
    !is.na(start_lat) & !is.na(start_lng) & !is.na(end_lng)
  )
df_07=read_csv(here("data_raw", "202307-capitalbikeshare-tripdata.csv"))%>%
  filter(
    !is.na(start_station_name) & !is.na(start_station_id) & start_station_name != "" & start_station_id != "" &
    !is.na(end_station_name) & !is.na(end_station_id) & end_station_name != "" & end_station_id != "" &
    !is.na(start_lat) & !is.na(start_lng) & !is.na(end_lng)
  )
df_08=read_csv(here("data_raw", "202308-capitalbikeshare-tripdata.csv"))%>%
  filter(
    !is.na(start_station_name) & !is.na(start_station_id) & start_station_name != "" & start_station_id != "" &
    !is.na(end_station_name) & !is.na(end_station_id) & end_station_name != "" & end_station_id != "" &
    !is.na(start_lat) & !is.na(start_lng) & !is.na(end_lng)
  )
df_09=read_csv(here("data_raw", "202309-capitalbikeshare-tripdata.csv"))%>%
  filter(
    !is.na(start_station_name) & !is.na(start_station_id) & start_station_name != "" & start_station_id != "" &
    !is.na(end_station_name) & !is.na(end_station_id) & end_station_name != "" & end_station_id != "" &
    !is.na(start_lat) & !is.na(start_lng) & !is.na(end_lng)
  )
df_10=read_csv(here("data_raw", "202310-capitalbikeshare-tripdata.csv"))%>%
filter(
    !is.na(start_station_name) & !is.na(start_station_id) & start_station_name != "" & start_station_id != "" &
    !is.na(end_station_name) & !is.na(end_station_id) & end_station_name != "" & end_station_id != "" &
    !is.na(start_lat) & !is.na(start_lng) & !is.na(end_lng)
  )
```
```{r}
all_data <- bind_rows(
  df_01, df_02, df_03, df_04, df_05, df_06, df_07, df_08, df_09, df_10,
  .id = "month"
)

df$started_at <- as.POSIXct(df$started_at, format = "%Y-%m-%d %H:%M:%S")

df$month <- format(df$started_at, "%Y-%m")

ggplot(df, aes(x = month)) +
  geom_bar() +
  labs(title = "Monthly Ride Counts",
       x = "Month",
       y = "Ride Counts") +
  theme_minimal()

```
```{r}
ggplot(all_data, aes(x = month, y = as.numeric(ended_at - started_at))) +
  geom_boxplot() +
  labs(title = "Average Ride Duration by Month",
       x = "Month",
       y = "Duration (minutes)") +
  theme_minimal()
```
```{r}
ggplot(all_data, aes(x = month, fill = rideable_type)) +
  geom_bar(position = "fill") +
  labs(title = "Popular Rideable Types by Month",
       x = "Month",
       y = "Proportion") +
  theme_minimal() +
  scale_y_continuous(labels = scales::percent_format(scale = 1))
```

